version: "3"

networks:
  sample-network:

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "21040:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_pass
      MYSQL_ROOT_PASSWORD: sample_pass_root
    volumes:
      - ./docker-compose/mysql/dump:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/conf:/etc/mysql/conf.d
      - ./docker-compose/mysql/mysql:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "21041:80"
    networks:
      - default
    environment:
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_pass_root
      MYSQL_ROOT_PASSWORD: sample_pass_root
